account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('forgot-password/', views.forgot_password, name="forgot_password"),
    path('new-password/<uidb64>/<token>/', views.new_password, name='new_password'),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register, name="register"),
    path('profile/', views.Profile, name="profile"),
    path('withdrawal/', views.request_withdrawal, name="request_withdrawal"),
]

adestra/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('smartlink/<int:placement_id>/<uuid:unique_id>/<slug:subid>/', views.redirect_to_ad, name='redirect_to_ad'),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('smartlinks/', views.direct_link, name="direct_link"),
    path('statistics/', views.statistics, name="statistics"),
    path('generate-link/', views.generate_link, name='generate_link'),

    path('notice/<int:notice_id>/', views.notice_detail, name='notice_detail'),
    
    path('contact/', views.contact, name="contact"),
    path('privacy-policy/', views.privacy, name="privacy"),
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/"
  data-template="vertical-menu-template-free">

<head>
  <meta charset="utf-8" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

  <title>{% block title %} {% endblock %} | Trafeek</title>

  <meta name="description" content="" />


  <meta name="google-site-verification" content="4FCTe2tWZMeoOUFF-qh9kMJydGcPx6SMCgSBHtfwNA4" />

  <!-- Favicon -->
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">

  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
    rel="stylesheet" />

  <!-- Icons. Uncomment required icon fonts -->
  <link rel="stylesheet" href="{% static '/assets/vendor/fonts/boxicons.css' %}" />

  <!-- Core CSS -->
  <link rel="stylesheet" href="{% static '/assets/vendor/css/core.css' %}" class="template-customizer-core-css" />
  <link rel="stylesheet" href="{% static '/assets/vendor/css/theme-default.css' %}"
    class="template-customizer-theme-css" />
  <link rel="stylesheet" href="{% static '/assets/css/demo.css' %}" />

  <!-- Vendors CSS -->
  <link rel="stylesheet" href="{% static '/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />

  <link rel="stylesheet" href="{% static '/assets/vendor/libs/apex-charts/apex-charts.css' %}" />

  {% block style %} {% endblock %}

  <!-- Page CSS -->


  <!-- Helpers -->
  <script src="{% static '/assets/vendor/js/helpers.js' %}"></script>

  <script src="{% static '/assets/js/config.js' %}"></script>
  <script type='text/javascript' src='//pl25638230.profitablecpmrate.com/03/95/8b/03958b0a54a0a75a82bee5055163e353.js'></script>
</head>

<body>
  <!-- Layout wrapper -->
  <div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
      <!-- Menu -->

      {% include 'partials/sidebar.html' %}
      <!-- / Menu -->

      <!-- Layout container -->
      <div class="layout-page">

        {% if request.user.is_approved != 'Active' %}
          <div class="container mt-2">
            <div class="alert alert-danger" role="alert">
              Your account is currently inactive. Please contact our support system.
              <div class="dropdown d-inline position-relative">
                <button
                  class="btn btn-sm btn-danger dropdown-toggle"
                  type="button"
                  id="contactDropdown"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Contact Us
                </button>
                <ul class="dropdown-menu" aria-labelledby="contactDropdown" style="z-index: 1200;">
                  <li>
                    <a class="dropdown-item" href="skype:{{setting.skype}}?chat" target="_blank">Skype</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="mailto:{{setting.email}}" target="_blank">Email</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        {% endif %}


        <!-- Navbar -->

        <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
          <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
            <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
              <i class="bx bx-menu bx-sm"></i>
            </a>
          </div>

          <div class="notice-container px-4 py-2 text-white rounded shadow-sm d-none d-md-flex align-items-center col-md-10 col-xl-8" style="background-color: #7291e6;">
            <b class="me-3">Notice:</b>
            <marquee behavior="scroll" direction="left" class="notice-text">
              {{setting.notice}}
            </marquee>
          </div>
          
          <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
            <ul class="navbar-nav flex-row align-items-center ms-auto">
              <li class="nav-item lh-1 me-3">
                Balance: ${{user_balance|floatformat:4}}
              </li>
              <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                  <div class="avatar avatar-online">
                    {% if request.user.avatar %}
                    <img src="{{request.user.avatar.url}}" alt class="w-px-40 h-auto rounded-circle" />
                    {% else %}
                    <img src="{% static 'assets/img/avatars/avatar1.jpeg' %}" alt class="w-px-40 h-auto rounded-circle" />
                    {% endif %}
                  </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li>
                    <a class="dropdown-item" href="{% url 'account:profile' %}">
                      <div class="d-flex">
                        <div class="flex-shrink-0 me-3">
                          <div class="avatar avatar-online">
                            {% if request.user.avatar %}
                            <img src="{{request.user.avatar.url}}" alt class="w-px-40 h-auto rounded-circle" />
                            {% else %}
                            <img src="{% static 'assets/img/avatars/avatar1.jpeg' %}" alt
                              class="w-px-40 h-auto rounded-circle" />
                            {% endif %}
                          </div>
                        </div>
                        <div class="flex-grow-1">
                          <span class="fw-semibold d-block">{{request.user.first_name}}
                            {{request.user.last_name}}</span>
                          <small class="text-muted">{{request.user.username}}</small>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <div class="dropdown-divider"></div>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'account:logout' %}">
                      <i class="bx bx-power-off me-2"></i>
                      <span class="align-middle">Log Out</span>
                    </a>
                  </li>
                </ul>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li>
                    <a class="dropdown-item" href="#">
                      <div class="d-flex">
                        <div class="flex-shrink-0 me-3">
                          <div class="avatar avatar-online">
                            {% if request.user.avatar %}
                            <img src="{{request.user.avatar.url}}" alt class="w-px-40 h-auto rounded-circle" />
                            {% else %}
                            <img src="{% static 'assets/img/avatars/1.png' %}" alt
                              class="w-px-40 h-auto rounded-circle" />
                            {% endif %}
                          </div>
                        </div>
                        <div class="flex-grow-1">
                          <span class="fw-semibold d-block">{{request.user.first_name}}
                            {{request.user.last_name}}</span>
                          <small class="text-muted">{{request.user.username}}</small>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <div class="dropdown-divider"></div>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'account:logout' %}">
                      <i class="bx bx-power-off me-2"></i>
                      <span class="align-middle">Log Out</span>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <i class="menu-icon text-dark tf-icons bx bx-bell" style="font-size: 28px;"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                  {% if bel_notices %}
                    {% for notice in bel_notices %}
                      <li>
                        <a class="dropdown-item" href="{% url 'core:notice_detail' notice.id %}">
                          <span class="align-middle">{{ notice.title }}</span>
                        </a>
                      </li>
                      {% if not forloop.last %}
                        <li>
                          <div class="dropdown-divider"></div>
                        </li>
                      {% endif %}
                    {% endfor %}
                  {% else %}
                    <li>No notices available.</li>
                  {% endif %}
                </ul>
                              
                <ul class="dropdown-menu dropdown-menu-end">
                  <li>
                    <a class="dropdown-item" href="#">
                      <div class="d-flex">
                        <div class="flex-shrink-0 me-3">
                          <div class="avatar avatar-online">
                            {% if request.user.avatar %}
                            <img src="{{request.user.avatar.url}}" alt class="w-px-40 h-auto rounded-circle" />
                            {% else %}
                            <img src="{% static 'assets/img/avatars/1.png' %}" alt
                              class="w-px-40 h-auto rounded-circle" />
                            {% endif %}
                          </div>
                        </div>
                        <div class="flex-grow-1">
                          <span class="fw-semibold d-block">{{request.user.first_name}}
                            {{request.user.last_name}}</span>
                          <small class="text-muted">{{request.user.username}}</small>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <div class="dropdown-divider"></div>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'account:logout' %}">
                      <i class="bx bx-power-off me-2"></i>
                      <span class="align-middle">Log Out</span>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>

        <!-- / Navbar -->

        {% block content %} {% endblock %}

        <!-- Content wrapper -->

        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
  </div>
  <!-- / Layout wrapper -->



  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="{% static 'assets/vendor/libs/jquery/jquery.js' %}"></script>
  <script src="{% static 'assets/vendor/libs/popper/popper.js' %}"></script>
  <script src="{% static 'assets/vendor/js/bootstrap.js' %}"></script>
  <script src="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

  <script src="{% static 'assets/vendor/js/menu.js' %}"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  <script src="{% static 'assets/vendor/libs/apex-charts/apexcharts.js' %}"></script>

  <!-- Main JS -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  <!-- Page JS -->
  <script src="{% static 'assets/js/dashboards-analytics.js' %}"></script>

  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>

templates/partials/sidebar.html
{% load static %}
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
      <a href="{% url 'core:index' %}" class="app-brand-link">
        <span class="app-brand-logo demo">
          <img src="{% static 'logo_21.png' %}" style="width: 200px;" />
        </span>
      </a>

      <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
        <i class="bx bx-chevron-left bx-sm align-middle"></i>
      </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
      <!-- Dashboard -->
      {% url 'core:dashboard' as dashboard_url %}
      <li class="menu-item {% if request.path == dashboard_url %}active{% endif %}">
        <a href="{% url 'core:dashboard' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-home-circle"></i>
          <div data-i18n="Analytics">Dashboard</div>
        </a>
      </li>

      {% url 'core:statistics' as statistics_url %}
      <li class="menu-item {% if request.path == statistics_url %}active{% endif %}">
        <a href="{% url 'core:statistics' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-bar-chart"></i>
          <div data-i18n="Analytics">Statistics</div>
        </a>
      </li>

      {% url 'core:direct_link' as direct_link_url %}
      <li class="menu-item {% if request.path == direct_link_url %}active{% endif %}">
        <a href="{% url 'core:direct_link' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-link"></i>
          <div data-i18n="Analytics">Smart Link</div>
        </a>
      </li>

      {% url 'account:request_withdrawal' as withdrawal %}
      <li class="menu-item {% if request.path == withdrawal %}active{% endif %}">
        <a href="{% url 'account:request_withdrawal' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-money"></i>
          <div data-i18n="Analytics">Withdrawal</div>
        </a>
      </li>

      {% url 'account:profile' as profile_url %}
      <li class="menu-item {% if request.path == profile_url %}active{% endif %}">
        <a href="{% url 'account:profile' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-user"></i>
          <div data-i18n="Analytics">Profile</div>
        </a>
      </li>

      <!-- <li class="menu-item">
        <a href="{% url 'core:contact' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-phone"></i>
          <div data-i18n="Analytics">Contact Us</div>
        </a>
      </li> -->

      <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
          <i class="menu-icon tf-icons bx bx-phone"></i>
          <div data-i18n="Account Settings">Contact Us</div>
        </a>
        <ul class="menu-sub">
          <li class="menu-item">
            <a href="skype:{{setting.skype}}?chat" class="menu-link">
              <div data-i18n="Account">Skype ID</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="mailto:{{setting.email}}" class="menu-link">
              <div data-i18n="Notifications">Email ID</div>
            </a>
          </li>
          
        </ul>
      </li>

    </ul>
  </aside>